export const deviceList: any = [
  "Samsung S22 Ultra 5G",
  "Galaxy S22+ Ultra 5G",
  "Galaxy S22 5G",
  "Galaxy S21 5G",
  "Galaxy S21 Ultra 5G",
  "Galaxy S21+ 5G",
  "Galaxy S20 & S20+",
  "Galaxy Z Flip",
  "Galaxy Z Flip3 5G",
  "Galaxy Z Fold3",
  "Galaxy Z Fold2",
  "Galaxy Fold",
  "Galaxy Note 20 Ultra",
  "Galaxy Note 20+",
  "Galaxy Note 20",
  "Samsung Watch4 LTE",
  "Samsung Watch4 Classic LTE",
  "Samsung Z Flip 4 5G",
  "Samsung Z Fold 4 5G",
  "Samsung Z Flip 5 5G",
  "Samsung Z Fold 5 5G",
  "Oppo Find X5 Pro",
  "Oppo Find X3 Pro",
  "Oppo Find X5",
  "Oppo A55s 5G",
  "Oppo Reno 5 A",
  "Huawei P40",
  "Huawei P40 Pro",
  "Huawei Mate P40 Pro",
  "Google Pixel 3",
  "Google Pixel 3 XL",
  "Google Pixel 3A",
  "Google Pixel 3A XL",
  "Google Pixel 4",
  "Google Pixel 4 XL",
  "Google Pixel 4a",
  "Google Pixel 4a 5G",
  "Google Pixel 5",
  "Google Pixel 6",
  "Google Pixel 6 Pro",
  "Motorola Razr 2019",
  "Microsoft Surface Duo",
  "Microsoft Surface Pro x",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 15 Plus",
  "iPhone 15",
  "iPhone 14",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 13",
  "iPhone 13 Mini",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 12",
  "iPhone 12 Mini",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Max",
  "iPhone XS & XS Max",
  "iPhone XR",
  "iPhone SE (2020 dan 2022)",
  "iPad 7",
  "iPad Air 3",
  "iPad Mini 5",
  "iPad Pro (11\")",
  "iPad Pro 2 (11\")",
  "iPad Air 4",
  "iPad Pro 3 (12,9\")",
  "Xiaomi 13T"
]
